[package]
name = "rust_tetris"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.4"
rodio = "0.20.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
